In [2]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [3]:
for i in range (3):
    print(list1[i])

1
2
3


In [4]:
list1 = [i for i in range(10)]
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
list2 = [[1,2,3,]for i in range(10)]
print(list2)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [6]:
list3 = [[j for j in range(5)] for i in range(5)]
print(list3)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [7]:
list4 = [[j*j for j in range(5)] for i in range(5)]
print(list4)

[[0, 1, 4, 9, 16], [0, 1, 4, 9, 16], [0, 1, 4, 9, 16], [0, 1, 4, 9, 16], [0, 1, 4, 9, 16]]


In [8]:
list5 = [[j+i for j in range(5)] for i in range(5)]
print(list5)

[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]]


In [9]:
list6 = [[3*i+j for j in range(3)] for i in range(3)]
print(list6)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [10]:
r = int(input("Enter the number of rows"))
c = int(input("Enter the number of columns"))
list1 = [int(x) for x in input().split()]
print("list in 1D:", list1)

a = []
for i in range(r):
    a.append([])
    for j in range(c):
        a[i].append(list1[c*i+j])
print("list in 2D:", a)

list in 1D: [1, 2, 3, 4]
list in 2D: [[1, 2], [3, 4]]


In [11]:
list1 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print("array:",list1)
rows = len(list1)
cols = len(list1[0])

print(rows,cols)

for j in range(cols):
    if j % 2 == 0:
        for i in range(rows):
            print(list1[i][j])
    else:
        i = rows - 1
        while(i >= 0):
            print(list1[i][j])
            i = i - 1

array: [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
4 3
1
4
7
10
11
8
5
2
3
6
9
12


In [12]:
import math
math.gcd(120,45)

15

In [13]:
#numpy is for better memory management
#faster computation

import numpy as np
demo = [10,20,30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [14]:
demo2 = [10,20,'30']
np.array(demo2)

array(['10', '20', '30'], dtype='<U11')

In [15]:
demo2 = [10,20,'xyz']
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U11')

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [18]:
np.zeros(5,int)
x1 = np.ones(5)
print(x1)

[1. 1. 1. 1. 1.]


In [19]:
x1[2] = "xyz"

ValueError: could not convert string to float: 'xyz'

In [20]:
y = np.zeros(10,int)
y.dtype

dtype('int32')

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
x5 = np.ones(5)

x5[3] = "2"
print(x5)

[1. 1. 1. 2. 1.]


In [23]:
new_array = np.zeros((3,4,5))
print(new_array)

new_array[0][1][2]
new_array[0][1]
new_array[0]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
new_array.shape

(3, 4, 5)

In [25]:
a = np.zeros(5)
print(a)
a[2:5] #starting from 2nd index upto 4th index

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [26]:
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(twoD_array[:,1])

[2 5 8]


In [28]:
new_twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(new_twoD_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
new_twoD_array[1:3,0]

array([4, 7])

In [30]:
new_twoD_array[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [31]:
import numpy as np
import math as m

In [32]:
x = [1,2,3]
y = [3,5,6]
x = x + 10
print(x)

TypeError: can only concatenate list (not "int") to list

In [33]:
x = np.array([1,2,3])
y = np.array([3,5,6])
x = x + 10
y = y + 10
print(x,y)

print(x + y)

[11 12 13] [13 15 16]
[24 27 29]


In [34]:
z = np.array(100,200,300,400)
print(y+z)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [35]:
print(x*2)
print(x*y)
print(x**3)

[22 24 26]
[143 180 208]
[1331 1728 2197]


In [36]:
print(x.mean())
print(x.sum())

12.0
36


In [37]:
p1 = np.array([2,2,2])
p2 = np.array([1,1,1])

val = ((p1 - p2)**2).sum()
print(val)

m.sqrt(val)


3


1.7320508075688772

In [38]:
pts = np.array([4,5,6,7])
value1 = ((pts - pts.mean())**2).sum()
print(value1)
m.sqrt(value1)

5.0


2.23606797749979

In [39]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])

print(m1.dot(m2)) # give you the dot product

32


In [40]:
import pandas as pd
from sklearn import datasets

In [41]:
iris_df = pd.read_csv("D:\Datasets\iris.csv")

In [42]:
print(iris_df)

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]


In [43]:
df = iris_df.copy()

In [74]:
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [45]:
df.tail(5)

sepallength  sepalwidth  petallength  petalwidth           class
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [46]:
print(df.shape)
print(df.dtypes)

(150, 5)
sepallength    float64
sepalwidth     float64
petallength    float64
petalwidth     float64
class           object
dtype: object


In [47]:
df["class"]

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

In [48]:
df.isnull()

sepallength  sepalwidth  petallength  petalwidth  class
0          False       False        False       False  False
1          False       False        False       False  False
2          False       False        False       False  False
3          False       False        False       False  False
4          False       False        False       False  False
..           ...         ...          ...         ...    ...
145        False       False        False       False  False
146        False       False        False       False  False
147        False       False        False       False  False
148        False       False        False       False  False
149        False       False        False       False  False

[150 rows x 5 columns]

In [49]:
df.isnull().sum()

sepallength    0
sepalwidth     0
petallength    0
petalwidth     0
class          0
dtype: int64

In [50]:
df.iloc[0:2,0:3]

sepallength  sepalwidth  petallength
0          5.1         3.5          1.4
1          4.9         3.0          1.4

In [51]:
df.drop(0)
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [52]:
new_df = df.drop(0)
new_df.head()

# to make it in place you can do the following - 
# df.drop(0, inplace = True)
# df.head()

sepallength  sepalwidth  petallength  petalwidth        class
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa

In [53]:
new_df.index

RangeIndex(start=1, stop=150, step=1)

In [54]:
new_df.index[0]

1

In [55]:
new_df.drop(new_df.index[0])

sepallength  sepalwidth  petallength  petalwidth           class
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
5            5.4         3.9          1.7         0.4     Iris-setosa
6            4.6         3.4          1.4         0.3     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[148 rows x 5 columns]

In [56]:
new_df.petalwidth > 0.2

1      False
2      False
3      False
4      False
5       True
       ...  
145     True
146     True
147     True
148     True
149     True
Name: petalwidth, Length: 149, dtype: bool

In [57]:
new_df.describe()

sepallength  sepalwidth  petallength  petalwidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [58]:
new_df[new_df.petalwidth > 0.2]

sepallength  sepalwidth  petallength  petalwidth           class
5            5.4         3.9          1.7         0.4     Iris-setosa
6            4.6         3.4          1.4         0.3     Iris-setosa
15           5.7         4.4          1.5         0.4     Iris-setosa
16           5.4         3.9          1.3         0.4     Iris-setosa
17           5.1         3.5          1.4         0.3     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[116 rows x 5 columns]

In [59]:
new_df[new_df.petalwidth > 0.2].describe()

sepallength  sepalwidth  petallength  petalwidth
count   116.000000  116.000000   116.000000  116.000000
mean      6.105172    2.963793     4.438793    1.496552
std       0.740369    0.419606     1.402406    0.599410
min       4.500000    2.000000     1.300000    0.300000
25%       5.600000    2.700000     4.000000    1.200000
50%       6.100000    3.000000     4.700000    1.500000
75%       6.600000    3.200000     5.400000    1.925000
max       7.900000    4.400000     6.900000    2.500000

In [81]:
print(new_df.iloc[0])

AttributeError: 'Index' object has no attribute 'iloc'